### ISSUE TITLE
Max health attribute not working correctly

### ISSUE THREAD

**Issue by JmKopecky** [JmKopecky/AeternumCraft#9]
When the max health attribute is used, removing the piece that gives the health causes health to appear to be over max health. Additionally, max health might appear to be correct based on the ui, but is actually not correct at times.

**Comment by iriskopecky** [comment]
Fixed health being inaccurate on item removal, but the max health attribute still doesn't update after one dies with the helmet on. It is still updating client side (UI) but get attribute command returns the normal value.
